# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  graphDocsRepo: 'https://github.com/finsharp/microsoft-graph-docs.git'
  graphDocsBranch: 'master'
  docSubPath: 'api-reference\beta'
  apiDoctorPath: '/ApiDoctor.Console/bin/Release/apidoc.exe'
  graphDocsPath: 'GraphDocs'
  

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  displayName: "Clone Docs"
  inputs:
    script: "git clone -b $(graphDocsBranch) https://github.com/finsharp/microsoft-graph-docs.git --recurse-submodules GraphDocs"

- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: "Test-Docs.ps1"
    arguments: -cleanUp -graphDocsPath '$(graphDocsPath)' -graphDocsRepo '$(graphDocsRepo)' -graphDocsBranch '$(graphDocsBranch)' -docSubPath '$(docSubPath)' -apiDoctorPath '$(apiDoctorPath)'
    #script: '# Write your powershell commands here.' # Required when targetType == Inline
    #errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
    #failOnStderr: false # Optional
    #ignoreLASTEXITCODE: false # Optional
    #pwsh: false # Optional
    #workingDirectory: # Optional

