# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  graphDocsRepo: 'https://github.com/microsoftgraph/microsoft-graph-docs.git'
  graphDocsBranch: 'master'
  betaDocsSubPath: 'api-reference\beta'
  v1DocsSubPath: 'api-reference\v1.0'
  apiDoctorPath: '/ApiDoctor.Console/bin/Release/apidoc.exe'
  graphDocsPath: 'GraphDocs'
  

steps:
- task: NuGetToolInstaller@0
  displayName: "Install Nuget.exe"

- task: NuGetCommand@2
  displayName: "Restore Packages for '$(solution)'"
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: "Build Solution for '$(solution)'' in '$(buildConfiguration)'"
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@1
  displayName: "Clone Microsoft Graph Docs"
  inputs:
    scriptType: inlineScript
    inlineScript: "git clone -b '$(graphDocsBranch)' '$(graphDocsRepo)' --recurse-submodules '$(graphDocsPath)' 2>&1 | Write-Host"

- task: PowerShell@2
  displayName: "Run ApiDoctor Against beta Docs"
  inputs:
    targetType: filePath
    filePath: "Test-Docs.ps1"
    arguments: -graphDocsPath '$(graphDocsPath)' -graphDocsRepo '$(graphDocsRepo)' -graphDocsBranch '$(graphDocsBranch)' -docSubPath '$(betaDocsSubPath)' -apiDoctorPath '$(apiDoctorPath)'
    errorActionPreference: continue
    
- task: PowerShell@2
  displayName: "Run ApiDoctor Against v1.0 Docs"
  inputs:
    targetType: filePath
    filePath: "Test-Docs.ps1"
    arguments: -cleanUp -graphDocsPath '$(graphDocsPath)' -graphDocsRepo '$(graphDocsRepo)' -graphDocsBranch '$(graphDocsBranch)' -docSubPath '$(v1DocsSubPath)' -apiDoctorPath '$(apiDoctorPath)'