; Graph Permissions Deployment Document

permissionDeployments = {
    permissionDeployments: {* permissionName => permissionDeployment} 
}

permissionDeployment = {
    id: tstr
    ? resourceAppId: tstr,
    environment: tstr
    scheme: tstr
    ? isHidden: bool .default false,
    ? isEnabled: bool .default false,
}


