//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDocs.Validation.UnitTests.Properties {
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("ApiDocs.Validation.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Resource with ISO 8601 timestamp, URL, and enumerated values.
        ///
        ///&lt;!-- { &quot;blockType&quot;: &quot;resource&quot;, &quot;@odata.type&quot;: &quot;example.resource&quot; } --&gt;
        ///```json
        ///{
        ///	&quot;year&quot;: 1234,
        ///	&quot;downloadUrl&quot;: &quot;url&quot;,
        ///	&quot;createdDateTime&quot;: &quot;timestamp&quot;,
        ///	&quot;season&quot;: &quot;summer | fall | winter | spring&quot;,
        ///	&quot;ownerName&quot;: &quot;rgregg&quot;,
        ///	&quot;contentType&quot;: &quot;string&quot;
        ///}
        ///```
        ///
        ///## Example request/response that&apos;s completely valid
        ///
        ///&lt;!-- { &quot;blockType&quot;: &quot;request&quot;, &quot;name&quot;: &quot;valid-response&quot; } --&gt;
        ///```http
        ///GET /timestamp
        ///```
        ///
        ///&lt;!-- { &quot;blockType&quot;: &quot;respon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResources {
            get {
                return ResourceManager.GetString("ExampleResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- { &quot;blockType&quot;: &quot;resource&quot;, &quot;@odata.type&quot;: &quot;test.simple&quot; } --&gt;
        ///```json
        ///{
        ///  &quot;prop1&quot;: &quot;testing&quot;,
        ///  &quot;prop2&quot;: &quot;simple&quot;,
        ///  &quot;prop3&quot;: &quot;waterbottle&quot;
        ///}
        ///```
        ///
        ///Here&apos;s an example where the server response should be verified against
        ///properties in the sample, even though we&apos;re truncating the results:
        ///
        ///&lt;!-- { &quot;blockType&quot;: &quot;request&quot;, &quot;name&quot;: &quot;simple-truncation-test&quot; } --&gt;
        ///```http
        ///GET /test_resource
        ///```
        ///
        ///Here&apos;s the expected response, as written in the documentation. No validation errors
        ///occur here becau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleValidateResponse {
            get {
                return ResourceManager.GetString("ExampleValidateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- { &quot;blockType&quot;: &quot;resource&quot;, &quot;@odata.type&quot;: &quot;oneDrive.item&quot; } --&gt;
        ///```json
        ///{
        ///	&quot;id&quot;: &quot;string&quot;,
        ///	&quot;lastModifiedDateTime&quot;: &quot;date-time&quot;,
        ///	&quot;name&quot;: &quot;string&quot;,
        ///	&quot;size&quot;: 218753122201,
        ///	&quot;webUrl&quot;: &quot;url&quot;,
        ///	&quot;children&quot;: [
        ///		{ &quot;@odata.type&quot;: &quot;oneDrive.item&quot; }
        ///	]
        ///}
        ///```
        ///
        ///&lt;!-- { &quot;blockType&quot;: &quot;request&quot;, &quot;name&quot;: &quot;drive-plus-children&quot; } --&gt;
        ///```http
        ///GET /drive/root?expand=children(select=id,name)
        ///```
        ///
        ///The request returns the collection items, with the children collection expanded.
        ///
        ///&lt;!-- { &quot;blockType&quot;: &quot;resp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleValidationSelectStatement {
            get {
                return ResourceManager.GetString("ExampleValidationSelectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- { &quot;blockType&quot;: &quot;resource&quot;, &quot;@odata.type&quot;: &quot;oneDrive.item&quot; } --&gt;
        ///```json
        ///{
        ///	&quot;id&quot;: &quot;string&quot;,
        ///	&quot;lastModifiedDateTime&quot;: &quot;date-time&quot;,
        ///	&quot;name&quot;: &quot;string&quot;,
        ///	&quot;size&quot;: 218753122201,
        ///	&quot;webUrl&quot;: &quot;url&quot;,
        ///	&quot;children&quot;: [
        ///		{ &quot;@odata.type&quot;: &quot;oneDrive.item&quot; }
        ///	]
        ///}
        ///```
        ///
        ///&lt;!-- { &quot;blockType&quot;: &quot;request&quot;, &quot;name&quot;: &quot;drive-plus-children&quot; } --&gt;
        ///```http
        ///GET /drive/root?expand=children(select=id,name)
        ///```
        ///
        ///The request returns the collection items, with the children collection expanded.
        ///
        ///&lt;!-- { &quot;blockType&quot;: &quot;resp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleValidationSelectStatementFailure {
            get {
                return ResourceManager.GetString("ExampleValidationSelectStatementFailure", resourceCulture);
            }
        }
    }
}
