name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./ApiDoctor.sln
    - name: Build
      run: dotnet build ./ApiDoctor.sln --no-restore
    - name: Test
      run: dotnet test ./ApiDoctor.sln --no-build --verbosity normal
